// src/components/ConversationList.vue
<script setup lang="ts">
// 对话侧栏：挂载时拉对话列表，点击向上抛选中 ID；顶部「+ 新对话」抛 new。
// 列表项展示真实状态点 + 标题 + 相对时间，hover 出 ⋯ 更多菜单（删除，留扩展位），当前选中高亮。
// 对齐 ChatGPT/Claude/Claude Code 侧栏惯例。
import { onMounted, ref, onBeforeUnmount, computed } from 'vue'
import { listConversations, deleteConversation, renameConversation } from '../api/client'
import type { Conversation } from '../api/types'
import { relativeTime, fullTime } from '../lib/format'
import { scanStatusMeta } from '../lib/scanStatus'

// mode 过滤：渗透会话页传 'active'、流量分析页传 'passive'——只列该模式会话，两模式互不混。
// 纯聊天会话（Mode 空）不属于任一模式，传了 mode 就不显示。不传则列全部（向后兼容）。
// allowNew：是否显示「+ 新对话」——active 可手动发起=true；passive 由流量驱动自动建会话=false。
// emptyHint：无会话时的空态文案（passive 需引导「挂代理收流量」，与 active 不同）。
const props = withDefaults(
  defineProps<{ activeId?: string; mode?: string; allowNew?: boolean; emptyHint?: string }>(),
  { allowNew: true },
)
const items = ref<Conversation[]>([])
const emit = defineEmits<{ select: [convID: string]; new: []; deleted: [convID: string] }>()

// 搜索过滤：先按 mode 过滤，再按标题（去前缀后）+ id 前缀匹配，纯前端（列表本就全量拉取）。
const query = ref('')
const filtered = computed(() => {
  let base = items.value
  if (props.mode) base = base.filter((c) => c.Mode === props.mode)
  const q = query.value.trim().toLowerCase()
  if (!q) return base
  return base.filter(
    (c) => fullTitle(c).toLowerCase().includes(q) || c.ID.toLowerCase().startsWith(q),
  )
})

async function refresh() {
  items.value = await listConversations()
}
onMounted(refresh)
defineExpose({ refresh })

// 自适应轮询：仅当列表存在「进行中(active)」对话时每 8s 刷新——感知后台对话跑完/状态变化，
// 彻底覆盖「看着对话 A、对话 B 后台跑完」场景。全部终态则不轮询（零浪费）；菜单开着时跳过（不打断操作）。
let pollTimer: number | undefined
onMounted(() => {
  pollTimer = window.setInterval(() => {
    if (menuOpen.value) return // 用户正在操作菜单，别刷新打断
    if (items.value.some((c) => c.RunStatus === 'active')) refresh()
  }, 8000)
})
onBeforeUnmount(() => {
  if (pollTimer) clearInterval(pollTimer)
})

// 真实运行态 → 中文标签 + 色（共享 scanStatusMeta，与顶部状态栏统一一套词）。用 RunStatus
// 派生真实态，不用僵尸 Status。
function statusMeta(c: Conversation) {
  return scanStatusMeta(c.RunStatus)
}

// 标题：去「我要扫描」前缀 + 截取 host 让列表更易读；空则回退短 id（智能标题由后端回填）。
function displayTitle(c: Conversation): string {
  const raw = (c.Title || '').replace(/^我要扫描\s*/, '').trim()
  if (!raw) return c.ID.slice(0, 8)
  const host = raw.match(/https?:\/\/([^/\s]+)/)?.[1]
  return host ? host + raw.replace(/https?:\/\/[^/\s]+/, '').slice(0, 24) : raw.slice(0, 40)
}

// 悬停 tooltip：展示完整标题（仅去「我要扫描」前缀，不截断）。
function fullTitle(c: Conversation): string {
  return (c.Title || '').replace(/^我要扫描\s*/, '').trim() || c.ID
}

// ⋯ 更多菜单：开/关 + 点外部关闭。
// 菜单经 Teleport 渲染到 body、用 fixed 视口坐标定位——逃离对话列表 ul 的 overflow 裁剪
// （否则底部/边缘列表项的下拉菜单会被 ul 的 overflow-y:auto 裁掉，显示不全）。
const menuOpen = ref<string>('')
const menuConv = ref<Conversation | null>(null)
const menuStyle = ref<Record<string, string>>({})
function toggleMenu(c: Conversation, ev: Event) {
  ev.stopPropagation()
  if (menuOpen.value === c.ID) {
    closeMenu()
    return
  }
  const r = (ev.currentTarget as HTMLElement).getBoundingClientRect()
  // 右对齐按钮、按钮下方 4px；左缘 clamp 防贴边溢出屏幕。
  menuStyle.value = { top: `${r.bottom + 4}px`, left: `${Math.max(8, r.right - 140)}px` }
  menuConv.value = c
  menuOpen.value = c.ID
}
function closeMenu() {
  menuOpen.value = ''
  menuConv.value = null
}
onMounted(() => document.addEventListener('click', closeMenu))
onBeforeUnmount(() => document.removeEventListener('click', closeMenu))

const deleting = ref<string>('')
// 扫描进行中提示文案（前端拦截 + 后端 409 共用一套话术）。
const SCAN_ACTIVE_HINT = '扫描进行中，无法删除。请先在对话页点「■ 停止扫描」，停止后再删除。'
async function onDelete(c: Conversation, ev: Event) {
  ev.stopPropagation()
  menuOpen.value = ''
  if (deleting.value) return
  // 活跃扫描不许删（业界惯例：先停后删，防「删了对话、扫描脱缰、UI 再停不掉」的孤儿）。
  // 前端拦一道（即时反馈），后端 409 兜底（防列表态过期 / 绕过前端）。
  if (c.RunStatus === 'active') {
    window.alert(SCAN_ACTIVE_HINT)
    return
  }
  if (!window.confirm(`删除对话「${displayTitle(c)}」？\n对话和消息会删除，扫描成果（漏洞/图）保留。`)) return
  deleting.value = c.ID
  try {
    await deleteConversation(c.ID)
    items.value = items.value.filter((x) => x.ID !== c.ID)
    emit('deleted', c.ID)
  } catch (e) {
    window.alert(e instanceof Error && e.message === 'SCAN_ACTIVE' ? SCAN_ACTIVE_HINT : '删除失败，请重试')
  } finally {
    deleting.value = ''
  }
}

// 行内重命名：菜单点「重命名」→ 该项切输入框、聚焦选中；Enter/失焦提交，Esc 取消。
// 乐观更新（本地先改、后端静默回填），失败回滚原标题并提示。
const renamingId = ref<string>('')
const renameText = ref<string>('')
// 回调 ref：v-if 内只渲染一个输入框，挂载时回调触发即聚焦选中（比 nextTick + 数组 ref 稳）。
function bindRenameInput(el: HTMLInputElement | null) {
  if (el) el.select()
}
function startRename(c: Conversation, ev: Event) {
  ev.stopPropagation()
  menuOpen.value = ''
  menuConv.value = null
  renamingId.value = c.ID
  renameText.value = fullTitle(c)
}
function cancelRename() {
  renamingId.value = ''
  renameText.value = ''
}
function setTitle(convID: string, title: string) {
  // 不可变更新：替换数组项，不就地改对象。
  items.value = items.value.map((x) => (x.ID === convID ? { ...x, Title: title } : x))
}
async function commitRename(c: Conversation) {
  if (renamingId.value !== c.ID) return // 已被 Esc 取消
  const next = renameText.value.trim()
  renamingId.value = ''
  const prev = c.Title || ''
  if (next === fullTitle(c)) return // 无变化
  setTitle(c.ID, next) // 乐观更新
  try {
    await renameConversation(c.ID, next)
  } catch {
    setTitle(c.ID, prev) // 回滚
    window.alert('重命名失败，请重试')
  }
}
</script>

<template>
  <aside class="conv-list">
    <div class="cl-head">
      <button v-if="props.allowNew" class="new-conv" @click="emit('new')">+ 新对话</button>
      <button class="refresh" :class="{ solo: !props.allowNew }" title="刷新列表" @click="refresh">↻</button>
    </div>
    <div class="cl-search">
      <input
        v-model="query"
        type="search"
        placeholder="搜索对话…"
        aria-label="搜索对话"
        spellcheck="false"
      />
    </div>
    <ul>
      <li
        v-for="c in filtered"
        :key="c.ID"
        :class="{ active: c.ID === props.activeId }"
        @click="renamingId === c.ID ? null : emit('select', c.ID)"
      >
        <span class="cl-dot" :class="'dot-' + statusMeta(c).key" :title="statusMeta(c).label" />
        <div class="cl-body">
          <input
            v-if="renamingId === c.ID"
            :ref="(el) => bindRenameInput(el as HTMLInputElement | null)"
            v-model="renameText"
            class="cl-rename"
            maxlength="80"
            @click.stop
            @keydown.enter.prevent="commitRename(c)"
            @keydown.esc.prevent="cancelRename"
            @blur="commitRename(c)"
          />
          <div v-else class="cl-title" :title="fullTitle(c)">{{ displayTitle(c) }}</div>
          <div class="cl-meta">
            <span class="cl-status" :class="'st-' + statusMeta(c).key">{{ statusMeta(c).label }}</span>
            <span v-if="c.FindingCount" class="cl-findings" :title="c.FindingCount + ' 个漏洞'">🐛 {{ c.FindingCount }}</span>
            <span class="cl-time" :title="fullTime(c.CreatedAt)">{{ relativeTime(c.CreatedAt) }}</span>
          </div>
        </div>
        <div class="cl-actions">
          <button class="cl-more" title="更多" @click="toggleMenu(c, $event)">⋯</button>
        </div>
      </li>
      <li v-if="!filtered.length" class="cl-empty">{{ query.trim() ? '无匹配对话' : (props.emptyHint || '暂无对话') }}</li>
    </ul>
    <!-- ⋯ 菜单 Teleport 到 body：fixed 视口定位，不被 ul overflow 裁剪 -->
    <Teleport to="body">
      <div v-if="menuConv" class="cl-menu" :style="menuStyle" @click.stop>
        <button class="cl-menu-item" @click="startRename(menuConv, $event)">✎ 重命名</button>
        <!-- 扫描进行中禁删（业界惯例：先停后删）；终态才出删除按钮。 -->
        <button
          v-if="menuConv.RunStatus === 'active'"
          class="cl-menu-item disabled-hint"
          disabled
          title="扫描进行中，先在对话页「■ 停止扫描」，停止后再删除"
        >
          ⏳ 扫描中 · 先停止再删
        </button>
        <button
          v-else
          class="cl-menu-item danger"
          :disabled="deleting === menuConv.ID"
          @click="onDelete(menuConv, $event)"
        >
          🗑 删除对话
        </button>
      </div>
    </Teleport>
  </aside>
</template>

<style scoped>
.conv-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-width: 0;
}
.cl-head {
  display: flex;
  gap: 6px;
}
.new-conv {
  flex: 1;
  padding: 8px;
  background: var(--accent);
  color: #fff;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
}
.refresh {
  width: 36px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: 8px;
  color: var(--muted);
  cursor: pointer;
}
.cl-search input {
  width: 100%;
  box-sizing: border-box;
  padding: 6px 10px;
  background: var(--surface-2);
  border: 1px solid var(--border);
  border-radius: 8px;
  color: var(--text);
  font-size: 12px;
  outline: none;
  transition: border-color var(--duration-fast, 150ms);
}
.cl-search input:focus {
  border-color: var(--accent);
}
.cl-search input::placeholder {
  color: var(--muted);
}
.cl-rename {
  width: 100%;
  box-sizing: border-box;
  padding: 2px 6px;
  background: var(--surface);
  border: 1px solid var(--accent);
  border-radius: 6px;
  color: var(--text);
  font-size: 13px;
  outline: none;
}
ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
  overflow-y: auto;
}
li {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  border-radius: 8px;
  cursor: pointer;
  transition: background var(--duration-fast, 150ms);
}
li:hover {
  background: var(--surface-2);
}
li.active {
  background: var(--surface-2);
  box-shadow: inset 2px 0 0 var(--accent);
}
.cl-dot {
  flex-shrink: 0;
  width: 8px;
  height: 8px;
  border-radius: 50%;
}
.cl-body {
  flex: 1;
  min-width: 0;
}
.cl-title {
  font-size: 13px;
  color: var(--text);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.cl-meta {
  display: flex;
  gap: 8px;
  align-items: center;
  margin-top: 2px;
}
.cl-status {
  font-size: 11px;
  font-weight: 600;
}
.cl-time {
  font-size: 11px;
  color: var(--muted);
  font-family: var(--mono);
  margin-left: auto;
}
/* 漏洞计数徽标：琥珀色 pill，一眼标出「这批流量出了几个洞」 */
.cl-findings {
  font-size: 10.5px;
  color: var(--sev-high, #f59e0b);
  background: color-mix(in srgb, var(--sev-high, #f59e0b) 14%, transparent);
  border-radius: 5px;
  padding: 0 6px;
  line-height: 1.5;
  flex-shrink: 0;
}
/* passive 无「新对话」时，↻ 独占一行铺满（不再是 active 那个 36px 方钮） */
.refresh.solo { width: 100%; }
/* 状态文字色（只 color） */
.st-active {
  color: #34d399;
}
.st-done {
  color: #38bdf8;
}
.st-aborted {
  color: #94a3b8;
}
.st-idle {
  color: #64748b;
}
/* 状态色点（只 background；进行中绿脉冲） */
.dot-active {
  background: #34d399;
  animation: cl-pulse 1.6s ease-in-out infinite;
}
.dot-done {
  background: #38bdf8;
}
.dot-aborted {
  background: #94a3b8;
}
.dot-idle {
  background: #64748b;
}
@keyframes cl-pulse {
  50% {
    opacity: 0.4;
  }
}
/* ⋯ 更多菜单 */
.cl-actions {
  position: relative;
  flex-shrink: 0;
}
.cl-more {
  width: 24px;
  height: 24px;
  border: none;
  background: transparent;
  color: var(--muted);
  border-radius: 6px;
  cursor: pointer;
  font-size: 16px;
  line-height: 1;
  opacity: 0;
  transition: opacity var(--duration-fast, 150ms), background var(--duration-fast, 150ms);
}
li:hover .cl-more,
.cl-more:focus {
  opacity: 1;
}
.cl-more:hover {
  background: var(--surface);
}
.cl-menu {
  position: fixed; /* Teleport 到 body + JS 视口坐标定位（top/left 由 menuStyle 注入） */
  z-index: 1000;
  min-width: 132px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  box-shadow: var(--shadow);
  padding: 4px;
}
.cl-menu-item {
  display: block;
  width: 100%;
  text-align: left;
  padding: 6px 10px;
  border: none;
  background: transparent;
  color: var(--text);
  font-size: 12px;
  border-radius: 6px;
  cursor: pointer;
}
.cl-menu-item:hover {
  background: var(--surface-2);
}
.cl-menu-item.danger:hover {
  background: rgba(239, 68, 68, 0.15);
  color: #ef4444;
}
.cl-menu-item:disabled {
  opacity: 0.5;
  cursor: default;
}
/* 扫描中禁删提示：muted 文字、悬停不高亮（读起来就是「不可点」）。 */
.cl-menu-item.disabled-hint {
  color: var(--muted);
}
.cl-menu-item.disabled-hint:hover {
  background: transparent;
}
.cl-empty {
  color: var(--muted);
  font-size: 12px;
  justify-content: center;
  cursor: default;
}
.cl-empty:hover {
  background: transparent;
}
</style>

// web/src/features/conversation/ConversationList.tsx
import { useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState, forwardRef } from 'react'
import { createPortal } from 'react-dom'
import { NavLink } from 'react-router-dom'
import { Bug, ChevronLeft, ChevronRight, Clock3, Pencil, Plus, RefreshCw, Search, Trash2 } from 'lucide-react'
import { deleteConversation, listConversations, renameConversation } from '@/api/client'
import type { Conversation } from '@/api/types'
import { fullTime, relativeTime } from '@/lib/format'
import { scanStatusMeta } from '@/lib/scanStatus'
import { cn } from '@/lib/utils'

export interface ConversationListHandle {
  refresh: () => Promise<void>
}

interface ConversationListProps {
  activeId?: string
  mode?: string
  allowNew?: boolean
  emptyHint?: string
  heading?: string
  onSelect: (convID: string) => void
  onNew: () => void
  onDeleted: (convID: string) => void
}

// 每页条数：侧栏高度有限，配合翻页没必要拉大页；与后端默认对齐（parseLimit 默认也是 30）。
const PAGE_SIZE = 30

// 标题：去「我要扫描」前缀 + 截取 host 让列表更易读；空则回退短 id（智能标题由后端回填）。
function displayTitle(c: Conversation): string {
  const raw = (c.Title || '').replace(/^我要扫描\s*/, '').trim()
  if (!raw) return c.ID.slice(0, 8)
  const host = raw.match(/https?:\/\/([^/\s]+)/)?.[1]
  return host ? host + raw.replace(/https?:\/\/[^/\s]+/, '').slice(0, 24) : raw.slice(0, 40)
}

// 悬停 tooltip：展示完整标题（仅去「我要扫描」前缀，不截断）。
function fullTitle(c: Conversation): string {
  return (c.Title || '').replace(/^我要扫描\s*/, '').trim() || c.ID
}

const SCAN_ACTIVE_HINT = '扫描进行中，无法删除。请先在对话页点「停止扫描」，停止后再删除。'

// 头部主控件共用尺寸：「+ 新会话」按钮 与 passive 下不可点的「流量批次」占位保持同一盒模型，
// 两个 tab 切换时头部高度、字重、圆角完全一致，不做「按钮 vs 文字」的降级展示。
const HEADER_CONTROL = 'flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg px-3 py-2.5 text-[13.5px] font-semibold transition-colors'

// 会话侧栏：按页拉会话（offset 翻页，见 api/client.ts listConversations 注释），点击向上抛选中 ID；
// 顶部「+ 新会话」抛 new。列表项展示序号 + 真实状态点 + 标题 + 相对时间，hover 出 ⋯ 更多菜单
// （删除/重命名），当前选中高亮。mode 过滤下沉到服务端——分页边界建立在已过滤集合上。
export const ConversationList = forwardRef<ConversationListHandle, ConversationListProps>(
  function ConversationList(
    { activeId, mode, allowNew = true, emptyHint, heading, onSelect, onNew, onDeleted },
    ref,
  ) {
    const [items, setItems] = useState<Conversation[]>([])
    const [offset, setOffset] = useState(0)
    const [hasMore, setHasMore] = useState(false)
    const [loading, setLoading] = useState(false)
    const [query, setQuery] = useState('')
    const [menuOpen, setMenuOpen] = useState('')
    const [menuConv, setMenuConv] = useState<Conversation | null>(null)
    const [menuStyle, setMenuStyle] = useState<{ top: string; left: string }>({ top: '0px', left: '0px' })
    const [deleting, setDeleting] = useState('')
    const [renamingId, setRenamingId] = useState('')
    const [renameText, setRenameText] = useState('')
    const menuOpenRef = useRef(menuOpen)
    menuOpenRef.current = menuOpen
    const itemsRef = useRef(items)
    itemsRef.current = items
    const offsetRef = useRef(offset)
    offsetRef.current = offset

    // load：拉某一页（o=offset）。翻页 / 轮询 / 手动刷新按钮共用，只是各自传入的 o 不同。
    const load = useCallback(
      async (o: number) => {
        setLoading(true)
        try {
          const { conversations, hasMore: hm } = await listConversations(PAGE_SIZE, o, mode ?? '')
          setItems(conversations)
          setHasMore(hm)
          setOffset(o)
        } finally {
          setLoading(false)
        }
      },
      [mode],
    )

    // 供外部（父组件）调用的 refresh：语义是「有新变化，给我最新视图」——回第 1 页，
    // 与「刷新列表」按钮/内部轮询（停留当前页，不打断浏览）区分开。
    const refreshFromTop = useCallback(() => load(0), [load])
    useImperativeHandle(ref, () => ({ refresh: refreshFromTop }), [refreshFromTop])

    useEffect(() => {
      void load(0)
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [mode])

    // 自适应轮询：仅当当前页存在「进行中(active)」会话时每 8s 刷新（停留当前页，不跳页）——
    // 感知后台会话跑完/状态变化。全部终态则不轮询；菜单开着时跳过（不打断操作）。
    useEffect(() => {
      const timer = window.setInterval(() => {
        if (menuOpenRef.current) return
        if (itemsRef.current.some((c) => c.RunStatus === 'active')) void load(offsetRef.current)
      }, 8000)
      return () => clearInterval(timer)
    }, [load])

    // 点外部关闭菜单。
    useEffect(() => {
      const close = () => {
        setMenuOpen('')
        setMenuConv(null)
      }
      document.addEventListener('click', close)
      return () => document.removeEventListener('click', close)
    }, [])

    // 搜索：仅在当前页内按标题（去前缀后）+ id 前缀过滤——分页后不再一次性拉全量，
    // 搜索范围随之收窄到当前页（这个数据量级下，配合 30 条/页，多数场景首页就够用）。
    const filtered = useMemo(() => {
      const q = query.trim().toLowerCase()
      if (!q) return items
      return items.filter((c) => fullTitle(c).toLowerCase().includes(q) || c.ID.toLowerCase().startsWith(q))
    }, [items, query])

    const pageNo = Math.floor(offset / PAGE_SIZE) + 1
    const prevPage = () => {
      if (offset <= 0 || loading) return
      void load(Math.max(0, offset - PAGE_SIZE))
    }
    const nextPage = () => {
      if (!hasMore || loading) return
      void load(offset + PAGE_SIZE)
    }

    const toggleMenu = (c: Conversation, ev: React.MouseEvent) => {
      ev.stopPropagation()
      if (menuOpen === c.ID) {
        setMenuOpen('')
        setMenuConv(null)
        return
      }
      const r = (ev.currentTarget as HTMLElement).getBoundingClientRect()
      setMenuStyle({ top: `${r.bottom + 4}px`, left: `${Math.max(8, r.right - 150)}px` })
      setMenuConv(c)
      setMenuOpen(c.ID)
    }

    const onDelete = async (c: Conversation, ev: React.MouseEvent) => {
      ev.stopPropagation()
      setMenuOpen('')
      if (deleting) return
      // 活跃扫描不许删（业界惯例：先停后删，防「删了会话、扫描脱缰、UI 再停不掉」的孤儿）。
      if (c.RunStatus === 'active') {
        window.alert(SCAN_ACTIVE_HINT)
        return
      }
      if (!window.confirm(`删除对话「${displayTitle(c)}」？\n对话和消息会删除，扫描成果（漏洞/图）保留。`)) return
      setDeleting(c.ID)
      try {
        await deleteConversation(c.ID)
        setItems((prev) => prev.filter((x) => x.ID !== c.ID))
        onDeleted(c.ID)
      } catch (e) {
        window.alert(e instanceof Error && e.message === 'SCAN_ACTIVE' ? SCAN_ACTIVE_HINT : '删除失败，请重试')
      } finally {
        setDeleting('')
      }
    }

    const startRename = (c: Conversation, ev: React.MouseEvent) => {
      ev.stopPropagation()
      setMenuOpen('')
      setMenuConv(null)
      setRenamingId(c.ID)
      setRenameText(fullTitle(c))
    }
    const cancelRename = () => {
      setRenamingId('')
      setRenameText('')
    }
    const setTitle = (convID: string, title: string) => {
      setItems((prev) => prev.map((x) => (x.ID === convID ? { ...x, Title: title } : x)))
    }
    const commitRename = async (c: Conversation) => {
      const next = renameText.trim()
      setRenamingId('')
      const prev = c.Title || ''
      if (next === fullTitle(c)) return // 无变化
      setTitle(c.ID, next) // 乐观更新
      try {
        await renameConversation(c.ID, next)
      } catch {
        setTitle(c.ID, prev) // 回滚
        window.alert('重命名失败，请重试')
      }
    }

    return (
      <aside className="flex h-full min-h-0 flex-col gap-2">
        {/* 主动/被动 tab：对话模块内部切换，两个 tab 是同一视图组件的两条路由。 */}
        <div className="flex flex-shrink-0 gap-1 rounded-[9px] bg-surface-2 p-0.5">
          <NavLink
            to="/conversations/active"
            className={({ isActive }) =>
              cn(
                'flex-1 rounded-[7px] py-1.5 text-center text-[12.5px] font-semibold text-muted transition-colors hover:text-text',
                isActive && 'bg-surface text-accent shadow-sm',
              )
            }
          >
            主动
          </NavLink>
          <NavLink
            to="/conversations/passive"
            className={({ isActive }) =>
              cn(
                'flex-1 rounded-[7px] py-1.5 text-center text-[12.5px] font-semibold text-muted transition-colors hover:text-text',
                isActive && 'bg-surface text-accent shadow-sm',
              )
            }
          >
            被动
          </NavLink>
        </div>
        <div className="flex flex-shrink-0 items-stretch gap-1.5">
          {allowNew ? (
            <button type="button" onClick={onNew} className={cn(HEADER_CONTROL, 'bg-accent text-white hover:bg-accent-hover')}>
              <Plus className="h-4 w-4" />
              新对话
            </button>
          ) : (
            <span
              aria-disabled="true"
              className={cn(HEADER_CONTROL, 'cursor-default border border-border bg-surface-2 text-muted')}
            >
              {heading || '对话'}
            </span>
          )}
          <button
            type="button"
            title="刷新列表"
            aria-label="刷新列表"
            onClick={() => void load(offset)}
            className="flex w-9 flex-shrink-0 items-center justify-center rounded-lg border border-border bg-surface-2 text-muted transition-colors hover:border-border-strong hover:text-text"
          >
            <RefreshCw className="h-4 w-4" />
          </button>
        </div>
        <div className="relative flex-shrink-0">
          <Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-faint" />
          <input
            type="search"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="搜索本页对话…"
            aria-label="搜索对话"
            spellCheck={false}
            className="w-full rounded-lg border border-border bg-surface-2 py-1.5 pl-8 pr-2.5 text-xs text-text outline-none placeholder:text-muted focus:border-accent"
          />
        </div>
        {items.length > 0 && (
          <div className="flex-shrink-0 px-0.5 pb-0.5 font-mono text-[11px] text-muted">
            {query.trim() ? `本页 ${filtered.length}/${items.length} 条匹配` : `第 ${pageNo} 页 · 本页 ${items.length} 条`}
          </div>
        )}
        <ul className="flex min-h-0 flex-1 flex-col gap-0.5 overflow-y-auto pr-0.5">
          {filtered.map((c, idx) => {
            const meta = scanStatusMeta(c.RunStatus)
            return (
              <li
                key={c.ID}
                onClick={() => renamingId !== c.ID && onSelect(c.ID)}
                className={cn(
                  'group flex flex-shrink-0 items-start gap-2 rounded-lg px-2.5 py-2.5 cursor-pointer transition-colors hover:bg-surface-2',
                  c.ID === activeId && 'bg-surface-2 shadow-[inset_2px_0_0_var(--accent)]',
                )}
              >
                <span className="mt-0.5 w-4 flex-shrink-0 text-center font-mono text-[10.5px] leading-[18px] text-faint">
                  {offset + idx + 1}
                </span>
                <span
                  className={cn(
                    'mt-[7px] h-2 w-2 flex-shrink-0 rounded-full',
                    meta.key === 'active' && 'animate-pulse',
                  )}
                  style={{ background: meta.color }}
                  title={meta.label}
                />
                <div className="min-w-0 flex-1">
                  {renamingId === c.ID ? (
                    <input
                      autoFocus
                      value={renameText}
                      onChange={(e) => setRenameText(e.target.value)}
                      maxLength={80}
                      onClick={(e) => e.stopPropagation()}
                      onFocus={(e) => e.currentTarget.select()}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter') {
                          e.preventDefault()
                          void commitRename(c)
                        } else if (e.key === 'Escape') {
                          e.preventDefault()
                          cancelRename()
                        }
                      }}
                      onBlur={() => void commitRename(c)}
                      className="w-full rounded-md border border-accent bg-surface px-1.5 py-0.5 text-[13px] text-text outline-none"
                    />
                  ) : (
                    <div className="flex items-center justify-between gap-2">
                      <span className="truncate text-[13px] font-medium text-text" title={fullTitle(c)}>
                        {displayTitle(c)}
                      </span>
                      <span
                        className="flex-shrink-0 whitespace-nowrap font-mono text-[10.5px] text-faint"
                        title={fullTime(c.CreatedAt)}
                      >
                        {relativeTime(c.CreatedAt)}
                      </span>
                    </div>
                  )}
                  <div className="mt-1.5 flex flex-wrap items-center gap-1.5">
                    <span
                      className="inline-flex items-center rounded-full px-1.5 py-0.5 text-[10.5px] font-semibold leading-none"
                      style={{ color: meta.color, background: `color-mix(in srgb, ${meta.color} 16%, transparent)` }}
                    >
                      {meta.label}
                    </span>
                    {!!c.FindingCount && (
                      <span
                        className="inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[10.5px] font-semibold leading-none text-sev-high"
                        style={{ background: 'color-mix(in srgb, var(--sev-high) 16%, transparent)' }}
                        title={`${c.FindingCount} 个漏洞`}
                      >
                        <Bug className="h-3 w-3" />
                        {c.FindingCount}
                      </span>
                    )}
                  </div>
                </div>
                <button
                  type="button"
                  title="更多"
                  aria-label="更多"
                  onClick={(ev) => toggleMenu(c, ev)}
                  className="mt-0.5 flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-md text-muted opacity-0 hover:bg-surface group-hover:opacity-100 focus:opacity-100"
                >
                  <span className="text-base leading-none">⋯</span>
                </button>
              </li>
            )
          })}
          {filtered.length === 0 && (
            <li className="cursor-default justify-center text-xs text-muted">
              {query.trim() ? '本页无匹配对话' : emptyHint || '暂无对话'}
            </li>
          )}
        </ul>
        {/* 翻页：offset 分页（非 keyset），仅当有上一页或下一页时才露出，避免单页时的多余控件。 */}
        {(offset > 0 || hasMore) && (
          <div className="flex flex-shrink-0 items-center justify-between gap-2 pt-0.5">
            <button
              type="button"
              aria-label="上一页"
              disabled={offset <= 0 || loading}
              onClick={prevPage}
              className="flex h-7 w-7 items-center justify-center rounded-md border border-border bg-surface-2 text-muted transition-colors hover:border-border-strong hover:text-text disabled:cursor-not-allowed disabled:opacity-40"
            >
              <ChevronLeft className="h-3.5 w-3.5" />
            </button>
            <span className="font-mono text-[11px] text-muted">第 {pageNo} 页</span>
            <button
              type="button"
              aria-label="下一页"
              disabled={!hasMore || loading}
              onClick={nextPage}
              className="flex h-7 w-7 items-center justify-center rounded-md border border-border bg-surface-2 text-muted transition-colors hover:border-border-strong hover:text-text disabled:cursor-not-allowed disabled:opacity-40"
            >
              <ChevronRight className="h-3.5 w-3.5" />
            </button>
          </div>
        )}
        {/* ⋯ 菜单挂到 body：fixed 视口坐标定位，不被 ul overflow 裁剪 */}
        {menuConv &&
          createPortal(
            <div
              className="fixed z-[1000] min-w-[148px] rounded-lg border border-border bg-surface p-1 shadow-lg"
              style={menuStyle}
              onClick={(e) => e.stopPropagation()}
            >
              <button
                type="button"
                onClick={(ev) => startRename(menuConv, ev)}
                className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-left text-xs text-text hover:bg-surface-2"
              >
                <Pencil className="h-3.5 w-3.5" />
                重命名
              </button>
              {menuConv.RunStatus === 'active' ? (
                <button
                  type="button"
                  disabled
                  title="扫描进行中，先在对话页「停止扫描」，停止后再删除"
                  className="flex w-full cursor-default items-center gap-2 rounded-md px-2.5 py-1.5 text-left text-xs text-muted opacity-50"
                >
                  <Clock3 className="h-3.5 w-3.5" />
                  扫描中 · 先停止再删
                </button>
              ) : (
                <button
                  type="button"
                  disabled={deleting === menuConv.ID}
                  onClick={(ev) => void onDelete(menuConv, ev)}
                  className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-left text-xs text-text hover:bg-red-500/15 hover:text-red-500 disabled:opacity-50"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                  删除对话
                </button>
              )}
            </div>,
            document.body,
          )}
      </aside>
    )
  },
)
