// src/components/cards/FindingCard.vue
<script setup lang="ts">
// 漏洞卡：write_finding 的 Result 只有 {id}，真正的字段在 Args（LLM 入参）。
// 解析 args → severity/summary/cwe/target(method+path)，按分级配色高亮。
import { computed } from 'vue'
import { severityTagColor } from '../../lib/severity'

const props = defineProps<{ args: string }>()

interface FindingArgs {
  summary?: string
  severity?: string
  cwe_id?: string
  owasp_category?: string
  target?: { method?: string; path?: string }
}
const f = computed<FindingArgs>(() => {
  try {
    return JSON.parse(props.args || '{}')
  } catch {
    return {}
  }
})
const sev = computed(() => (f.value.severity || 'info').toLowerCase())
const tag = computed(() => severityTagColor(sev.value))
</script>

<template>
  <div class="finding-card" data-card="finding" :style="{ '--sev': tag.textColor }">
    <span class="badge" :style="{ background: tag.color, color: tag.textColor, borderColor: tag.borderColor }">
      {{ sev.toUpperCase() }}
    </span>
    <div class="body">
      <div class="summary">{{ f.summary || '(无标题)' }}</div>
      <div class="meta">
        <span v-if="f.target?.method || f.target?.path" class="target">
          <span class="method">{{ f.target?.method || 'GET' }}</span>{{ f.target?.path }}
        </span>
        <span v-if="f.cwe_id" class="tag">{{ f.cwe_id }}</span>
        <span v-if="f.owasp_category" class="tag">{{ f.owasp_category }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.finding-card {
  display: flex;
  gap: 12px;
  align-items: flex-start;
  padding: 12px 14px;
  border: 1px solid var(--border);
  border-left: 3px solid var(--sev, var(--sev-high));
  border-radius: var(--radius);
  background: var(--surface);
}
.badge {
  flex-shrink: 0;
  font-family: var(--mono);
  font-size: 11px;
  font-weight: 700;
  padding: 2px 8px;
  border-radius: 5px;
  border: 1px solid;
}
.body { min-width: 0; }
.summary { font-size: 14px; line-height: 1.5; font-weight: 500; }
.meta { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 6px; font-size: 12px; }
.target { font-family: var(--mono); color: var(--muted); word-break: break-all; }
.method { color: var(--accent); font-weight: 700; margin-right: 4px; }
.tag {
  font-family: var(--mono);
  color: var(--muted);
  background: var(--surface-2);
  padding: 1px 7px;
  border-radius: 5px;
}
</style>

// web/src/features/conversation/cards/FindingCard.tsx
import { severityTagColor } from '@/lib/severity'

interface FindingCardProps {
  args: string
}

interface FindingArgs {
  summary?: string
  severity?: string
  cwe_id?: string
  owasp_category?: string
  target?: { method?: string; path?: string }
}

function parseArgs(args: string): FindingArgs {
  try {
    return JSON.parse(args || '{}')
  } catch {
    return {}
  }
}

// 漏洞卡：write_finding 的 Result 只有 {id}，真正的字段在 Args（LLM 入参）。
// 解析 args → severity/summary/cwe/target(method+path)，按分级配色高亮。
export function FindingCard({ args }: FindingCardProps) {
  const f = parseArgs(args)
  const sev = (f.severity || 'info').toLowerCase()
  const tag = severityTagColor(sev)

  return (
    <div
      data-card="finding"
      className="flex items-start gap-3 rounded-[10px] border border-border border-l-[3px] bg-surface px-3.5 py-3"
      style={{ borderLeftColor: tag.textColor }}
    >
      <span
        className="flex-shrink-0 rounded-md border px-2 py-0.5 font-mono text-[11px] font-bold"
        style={{ background: tag.color, color: tag.textColor, borderColor: tag.borderColor }}
      >
        {sev.toUpperCase()}
      </span>
      <div className="min-w-0">
        <div className="text-sm font-medium leading-normal">{f.summary || '(无标题)'}</div>
        <div className="mt-1.5 flex flex-wrap gap-2 text-xs">
          {(f.target?.method || f.target?.path) && (
            <span className="break-all font-mono text-muted">
              <span className="mr-1 font-bold text-accent">{f.target?.method || 'GET'}</span>
              {f.target?.path}
            </span>
          )}
          {f.cwe_id && <span className="rounded-md bg-surface-2 px-1.5 py-0.5 font-mono text-muted">{f.cwe_id}</span>}
          {f.owasp_category && (
            <span className="rounded-md bg-surface-2 px-1.5 py-0.5 font-mono text-muted">{f.owasp_category}</span>
          )}
        </div>
      </div>
    </div>
  )
}
