// src/components/cards/ToolCallCard.vue
<script setup lang="ts">
// 工具调用卡：折叠头（工具名）+ 展开看美化后的入参 JSON。按 agent 名着左边框 + chip 色，区分谁在调用。
import { computed, ref } from 'vue'
import { agentAccent } from '../../lib/agentColor'
const props = defineProps<{ tool: string; args: string; agentName?: string }>()
const open = ref(false)
const pretty = computed(() => {
  if (!props.args) return ''
  try {
    return JSON.stringify(JSON.parse(props.args), null, 2)
  } catch {
    return props.args
  }
})
const hasArgs = computed(() => !!pretty.value && pretty.value !== '{}')
const accent = computed(() => agentAccent(props.agentName)) // 每个 agent 独立色
</script>

<template>
  <div
    class="tool-call"
    :class="{ 'has-agent': !!agentName }"
    :style="{ '--ag': accent.accent, '--ag-soft': accent.soft }"
    data-card="tool-call"
  >
    <button class="head" :class="{ open }" @click="open = !open">
      <span class="caret">▸</span>
      <span class="dot" />
      <span class="label">调用</span>
      <code class="tool">{{ tool }}</code>
      <span v-if="agentName" class="agent">{{ agentLabel(agentName) }}</span>
    </button>
    <pre v-if="open && hasArgs" class="args">{{ pretty }}</pre>
  </div>
</template>

<style scoped>
.tool-call { align-self: flex-start; max-width: 85%; }
.head {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 6px 12px;
  cursor: pointer;
  font-size: 13px;
  color: var(--text);
}
.head:hover { border-color: var(--accent); }
.caret { color: var(--muted); transition: transform 0.15s; font-size: 11px; }
.head.open .caret { transform: rotate(90deg); }
.dot { width: 6px; height: 6px; border-radius: 50%; background: var(--accent); }
.label { color: var(--muted); }
.tool { font-family: var(--mono); color: var(--accent); font-weight: 600; }
.agent {
  font-family: var(--mono);
  font-size: 10.5px;
  color: var(--muted);
  background: var(--surface-2);
  border-radius: 4px;
  padding: 0 6px;
}
/* 按 agent 名着色（--ag 由 inline style 注入）：左竖线 + chip 同色，每个 agent 一色 */
.tool-call.has-agent .head { border-left: 2px solid var(--ag); }
.tool-call.has-agent .agent { color: var(--ag); background: var(--ag-soft); }
.args {
  margin: 6px 0 0;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 10px;
  font-size: 12px;
  max-height: 280px;
  overflow: auto;
}
</style>

// web/src/features/conversation/cards/ToolCallCard.tsx
import { useState } from 'react'
import { agentAccent, agentLabel } from '@/lib/agentColor'
import { cn } from '@/lib/utils'

interface ToolCallCardProps {
  tool: string
  args: string
  agentName?: string
}

function prettyArgs(args: string): string {
  if (!args) return ''
  try {
    return JSON.stringify(JSON.parse(args), null, 2)
  } catch {
    return args
  }
}

// 工具调用卡：折叠头（工具名）+ 展开看美化后的入参 JSON。按 agent 名着左边框 + chip 色，区分谁在调用。
export function ToolCallCard({ tool, args, agentName }: ToolCallCardProps) {
  const [open, setOpen] = useState(false)
  const pretty = prettyArgs(args)
  const hasArgs = !!pretty && pretty !== '{}'
  const accent = agentAccent(agentName) // 每个 agent 独立色

  return (
    <div data-card="tool-call" className="self-start max-w-[85%]">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        style={agentName ? { borderLeft: `2px solid ${accent.accent}` } : undefined}
        className={cn(
          'inline-flex items-center gap-2 rounded-md border border-border bg-surface px-3 py-1.5 text-[13px] text-text',
          'hover:border-accent',
        )}
      >
        <span className={cn('text-[11px] text-muted transition-transform', open && 'rotate-90')}>▸</span>
        <span className="h-1.5 w-1.5 rounded-full bg-accent" />
        <span className="text-muted">调用</span>
        <code className="font-mono font-semibold text-accent">{tool}</code>
        {agentName && (
          <span
            className="rounded px-1.5 py-0 font-mono text-[10.5px]"
            style={{ color: accent.accent, background: accent.soft }}
          >
            {agentLabel(agentName)}
          </span>
        )}
      </button>
      {open && hasArgs && (
        <pre className="mt-1.5 max-h-[280px] overflow-auto rounded-[6px] border border-border bg-background p-2.5 text-xs">
          {pretty}
        </pre>
      )}
    </div>
  )
}
