// src/components/cards/ToolResultCard.vue
<script setup lang="ts">
// 工具结果卡：状态点(成功/错误) + 工具名 + 耗时，折叠看美化结果；错误默认展开。按 agent 名着色。
import { computed, ref } from 'vue'
import { agentAccent } from '../../lib/agentColor'
const props = defineProps<{ tool: string; result: string; durationMs: number; err: string; agentName?: string }>()
const open = ref(!!props.err)
const accent = computed(() => agentAccent(props.agentName)) // 每个 agent 独立色
const pretty = computed(() => {
  const raw = props.err || props.result
  if (!raw) return ''
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return raw
  }
})
const preview = computed(() => {
  const s = (props.err || props.result || '').replace(/\s+/g, ' ').trim()
  return s.length > 64 ? s.slice(0, 64) + '…' : s
})
</script>

<template>
  <div
    class="tool-result"
    :class="{ 'has-agent': !!agentName }"
    :style="{ '--ag': accent.accent, '--ag-soft': accent.soft }"
    data-card="tool-result"
    :data-error="!!err"
  >
    <button class="head" :class="{ open }" @click="open = !open">
      <span class="caret">▸</span>
      <span class="dot" :class="{ err: !!err }" />
      <code class="tool">{{ tool }}</code>
      <span class="dur">{{ durationMs }}ms</span>
      <span v-if="agentName" class="agent">{{ agentName }}</span>
      <span v-if="!open" class="preview">{{ preview }}</span>
    </button>
    <pre v-if="open" class="out" :class="{ err: !!err }">{{ pretty }}</pre>
  </div>
</template>

<style scoped>
.tool-result { align-self: flex-start; max-width: 85%; }
.head {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 6px 12px;
  cursor: pointer;
  font-size: 12.5px;
  color: var(--text);
  text-align: left;
}
.head:hover { border-color: var(--border-strong); }
.tool-result[data-error='true'] .head { border-color: var(--sev-critical); }
.caret { color: var(--muted); transition: transform 0.15s; font-size: 11px; }
.head.open .caret { transform: rotate(90deg); }
.dot { width: 6px; height: 6px; border-radius: 50%; background: var(--success); flex-shrink: 0; }
.dot.err { background: var(--sev-critical); }
.agent {
  font-family: var(--mono);
  font-size: 10.5px;
  color: var(--muted);
  background: var(--surface-2);
  border-radius: 4px;
  padding: 0 6px;
  flex-shrink: 0;
}
/* 按 agent 名着色（--ag 由 inline style 注入）：左竖线 + chip 同色；状态点 dot 仍绿/红表成功失败，与 agent 色正交 */
.tool-result.has-agent .head { border-left: 2px solid var(--ag); }
.tool-result.has-agent .agent { color: var(--ag); background: var(--ag-soft); }
.tool { font-family: var(--mono); color: var(--muted); }
.dur { color: var(--muted); font-size: 11px; }
.preview { color: var(--muted); font-family: var(--mono); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.out {
  margin: 6px 0 0;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 10px;
  font-size: 12px;
  max-height: 280px;
  overflow: auto;
}
.out.err { color: var(--sev-critical); border-color: var(--sev-critical); }
</style>

// web/src/features/conversation/cards/ToolResultCard.tsx
import { useState } from 'react'
import { agentAccent, agentLabel } from '@/lib/agentColor'
import { cn } from '@/lib/utils'

interface ToolResultCardProps {
  tool: string
  result: string
  durationMs: number
  err: string
  agentName?: string
}

function prettyResult(err: string, result: string): string {
  const raw = err || result
  if (!raw) return ''
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return raw
  }
}

function preview(err: string, result: string): string {
  const s = (err || result || '').replace(/\s+/g, ' ').trim()
  return s.length > 64 ? s.slice(0, 64) + '…' : s
}

// 工具结果卡：状态点(成功/错误) + 工具名 + 耗时，折叠看美化结果；错误默认展开。按 agent 名着色。
export function ToolResultCard({ tool, result, durationMs, err, agentName }: ToolResultCardProps) {
  const [open, setOpen] = useState(!!err)
  const accent = agentAccent(agentName) // 每个 agent 独立色
  const pretty = prettyResult(err, result)
  const previewText = preview(err, result)

  return (
    <div data-card="tool-result" data-error={!!err} className="self-start max-w-[85%]">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        style={agentName ? { borderLeft: `2px solid ${accent.accent}` } : undefined}
        className={cn(
          'flex w-full items-center gap-2 rounded-md border border-border bg-surface px-3 py-1.5 text-left text-[12.5px] text-text',
          'hover:border-border-strong',
          err && 'border-sev-critical',
        )}
      >
        <span className={cn('text-[11px] text-muted transition-transform', open && 'rotate-90')}>▸</span>
        <span className={cn('h-1.5 w-1.5 flex-shrink-0 rounded-full', err ? 'bg-sev-critical' : 'bg-emerald-500')} />
        <code className="font-mono text-muted">{tool}</code>
        <span className="text-[11px] text-muted">{durationMs}ms</span>
        {agentName && (
          <span
            className="flex-shrink-0 rounded px-1.5 py-0 font-mono text-[10.5px]"
            style={{ color: accent.accent, background: accent.soft }}
          >
            {agentLabel(agentName)}
          </span>
        )}
        {!open && <span className="overflow-hidden truncate font-mono text-muted">{previewText}</span>}
      </button>
      {open && (
        <pre
          className={cn(
            'mt-1.5 max-h-[280px] overflow-auto rounded-[6px] border border-border bg-background p-2.5 text-xs',
            err && 'border-sev-critical text-sev-critical',
          )}
        >
          {pretty}
        </pre>
      )}
    </div>
  )
}
